### ISSUE TITLE
Object::Iterate has no version in 02packages.details.txt

### ISSUE THREAD

**Issue by eserte** [briandfoy/object-iterate#16]
See subject. My fresh copy of 02packages.details.txt.gz contains the following lines:
```
Object::Iterate                   undef  B/BD/BDFOY/Object-Iterate-1.146.tar.gz
Object::Iterate::Tester           1.146  B/BD/BDFOY/Object-Iterate-1.146.tar.gz
```

At least this is causing problems when building a package using `dh-make-perl`.

**Comment by briandfoy** [comment]
huh, let me release a new version to get it reindexed. I figure this is a problem with PAUSE though.

**Comment by eserte** [comment]
Maybe PAUSE is confused by the preprocess script? But let's wait if it gets fixed by the new version...

**Comment by eserte** [comment]
1.148 works. And dh-make-perl works now, too.

**Comment by briandfoy** [comment]
Yes, it was finding a file I didn't intend, so I adjusted the no_index. Now it looks okay.
